// ─────────────────────────────────────────────────────────────────────────────
// Wörtle Wortliste: 5-Buchstaben deutsche Wörter (mit Umlauten, ohne ß)
// Wird sowohl für Antworten als auch für gültige Rateversuche genutzt.
// ─────────────────────────────────────────────────────────────────────────────
window.WOERTLE_WORDS = [
  // A
  "ABEND","ACHSE","ACHTE","ACHTS","ACKER","ADERN","ADLER","AGENT","AKTEN","AKTIE",
  "ALARM","ALBEN","ALGEN","ALLEE","ALLEM","ALLEN","ALLER","ALLES","ALPEN","ALTAR",
  "ALTEM","ALTEN","ALTER","ALTES","AMPEL","AMSEL","ÄMTER","ANGEL","ANGST","ANKER",
  "ANRUF","ANSEH","ANZUG","APFEL","ARENA","ÄRGER","ARMEE","ARMEN","ARMER","ARMES",
  "ARTEN","ARZTE","ARZTS","ASIAT","ASIEN","ATLAS","ATOLL","ATOME","AUDIO","AUGEN",
  "AUREN","AUTOR","AUTOS","AVISO","AXIOM",

  // B
  "BABYS","BACKE","BADEN","BADET","BAHRE","BÄCKER","BAHNE","BAKEN","BANDE","BANDS",
  "BANGE","BANGT","BANGE","BANNE","BARDE","BAREN","BARKE","BARON","BARRE","BAUCH",
  "BAUEN","BAUER","BAUES","BÄUME","BAUMS","BAYER","BEBEN","BEBOP","BECHE","BEERE",
  "BEFEHL","BEGINN","BEIGE","BEINE","BEKEN","BELLE","BERGE","BERLI","BESEN","BESTE",
  "BETEN","BETET","BETTE","BEUEL","BEULE","BEUTE","BEVOR","BIBER","BIENE","BIEST",
  "BIETE","BIKER","BILDE","BIRKE","BIRNE","BISON","BISSE","BITTE","BLAME","BLANK",
  "BLASE","BLATT","BLAUE","BLAUS","BLECH","BLEND","BLICK","BLIND","BLITZ","BLOCK",
  "BLOND","BLOSS","BLUME","BLUSE","BLÜTE","BODEN","BOGEN","BOHNE","BOMBE","BONUS",
  "BOOTE","BORDE","BOSSE","BOTEN","BOWLE","BOXEN","BRACK","BRAND","BRAUE","BRAUN",
  "BRAUT","BREIE","BREIT","BREMS","BRETT","BRIEF","BRISE","BRUCH","BRUST","BUBEN",
  "BUCHE","BUCHT","BÜGEL","BÜHNE","BÜRDE","BÜRGE","BUNDE","BUNDS","BUNTE","BUNTS",
  "BURGE","BURGS","BUSCH","BÜSTE","BYTES","BYZAN",

  // C
  "CAFES","CAMPS","CHAOS","CHEFS","CHILE","CHORE","CHORS","CLOWN","CLUBS","COACH",
  "CODES","COMIC",

  // D
  "DACHS","DAMEN","DAMPF","DANKE","DANKT","DARAN","DARIN","DATEN","DAUER","DAVON",
  "DECKE","DEGEN","DEIBE","DEICH","DEINE","DELLE","DEMOS","DENKE","DENKT","DEREN",
  "DESSEN","DEUTE","DEUTS","DICHT","DICKE","DICKS","DIELE","DIESE","DINGE","DINGS",
  "DIODE","DOCKS","DOGGE","DOMEN","DOMES","DORFE","DORFS","DOSEN","DOSIS","DRAHT",
  "DRAMA","DRANG","DREHE","DREHT","DRINK","DROGE","DROHT","DROSS","DRUCK","DRUSE",
  "DÜFTE","DUFTE","DULDE","DUNKEL","DÜNNE","DÜNNS","DUNST","DUPLO","DURST","DUSCHE",
  "DUTZEND",

  // E
  "EBBEN","ECHOS","ECHTE","ECKEN","ECKIG","EDDEN","EDLEM","EDLEN","EDLER","EDLES",
  "EHRE","EHREN","EICHE","EIGEN","EILIG","EIMER","EINER","EINES","EISEN","EITER",
  "ELBEN","ELFEN","ELITE","ENDET","ENGEL","ENGEM","ENGEN","ENGER","ENGES","ENKEL",
  "ENORM","ENTER","EPHEU","EPOCHE","ERBEN","ERBSE","ERDEN","ERLEN","ERNST","ESCHE",
  "ESEL","ESELN","ESELS","ESSEN","ESSER","ETAGE","ETHIK","ETUIS","EULEN","EUREM",
  "EUREN","EURER","EURES","EVENT","EWIGE","EWIGS",

  // F
  "FÄCHER","FAHRE","FAHRT","FAKIR","FALKE","FALLE","FALLS","FALSCH","FANGE","FANGS",
  "FÄNGT","FARBE","FASER","FASSE","FASST","FAULE","FAUST","FAXEN","FEDER","FEHLE",
  "FEHLT","FEIER","FEILE","FELDE","FELDS","FELLE","FELLS","FELSE","FELSS","FERN",
  "FERNE","FERSE","FESSE","FESTE","FETT","FETTE","FETTS","FEUER","FICKE","FIESE",
  "FILME","FILMS","FINDE","FINGER","FINNE","FIRMA","FIRST","FISCH","FIXES","FLACH",
  "FLAUM","FLECK","FLINK","FLIRT","FLOTE","FLOTT","FLÖTE","FLUCH","FLÜGE","FLUGS",
  "FLURE","FLURS","FLUSS","FOLGE","FOLGT","FOLIE","FONDS","FORST","FOTOS","FRACK",
  "FRAGE","FRAGT","FRANS","FRAUS","FRECH","FREIE","FRIST","FROHE","FROMM","FRONT",
  "FROST","FRÜHE","FRÜHS","FÜCHSE","FUCHS","FUHRE","FUHRS","FÜLLE","FUNDE","FUNDS",
  "FUNKE","FUNKS","FUSSE","FUTTER",

  // G
  "GABEL","GABEN","GAGEN","GALLE","GANZE","GANZS","GARDE","GARNE","GARNS","GASEN",
  "GASSE","GÄSTE","GASTE","GATTE","GEBEN","GEBET","GEBOT","GEDEN","GEDIE","GEHEN",
  "GEHTE","GEIER","GEIGE","GEIST","GELB","GELBE","GELBS","GELDE","GELDS","GELEN",
  "GEMSE","GENAU","GENEN","GENIE","GENRE","GENUG","GERN","GIBT","GIERS","GIFTE",
  "GIFTS","GLANZ","GLASE","GLAUB","GLEIS","GLIED","GLOBE","GLÜCK","GNADE","GNOME",
  "GOLDE","GOLDS","GOLEM","GOLFS","GONGS","GOTTS","GRABS","GRABE","GRABT","GRADE",
  "GRADS","GRAMM","GRAMS","GRASE","GRAUE","GRAUS","GREIF","GREIS","GRIES","GRIFF",
  "GRILL","GRIMM","GRIND","GROLL","GROSS","GRUBE","GRUFT","GRUND","GRUSS","GULASCH",
  "GUMMI","GUNST","GURKE","GURTE","GURTS","GUTEM","GUTEN","GUTER","GUTES",

  // H
  "HAARE","HAARS","HABEN","HACKE","HAGEL","HAGER","HAHNE","HAKEN","HALLE","HALLO",
  "HALSE","HALSS","HALTE","HALTS","HAMME","HÄMME","HAMS","HÄNDE","HÄNGE","HAPPE",
  "HARFE","HARKE","HARTE","HASCH","HASEL","HASEN","HASSE","HASST","HAUBE","HAUCH",
  "HAUEN","HAUER","HAUFE","HAUPT","HAUSE","HAUSS","HÄUTE","HAUTE","HEBEL","HEBEN",
  "HECHT","HECKE","HEERE","HEERS","HEFEN","HEFTE","HEFTS","HEIDE","HEILE","HEIMS",
  "HEIRA","HEISS","HEIZE","HEIZT","HELDS","HELFE","HELLE","HELMS","HEMDS","HENNE",
  "HEPRE","HERDE","HEREIN","HERME","HERRS","HERZE","HERZS","HEUER","HEXEN","HIRSE",
  "HIRTE","HOBEL","HOFES","HOFFE","HOFFT","HOHEM","HOHEN","HOHER","HOHES","HOHLE",
  "HÖHLE","HÖLLE","HOLST","HOLZE","HOLZS","HONIG","HÖREN","HORDE","HORNS","HORST",
  "HOSEN","HOTEL","HÜGEL","HUHN","HÜLLE","HÜLSE","HÜFTE","HUNDE","HUNDS","HUPEN",
  "HÜRDE","HÜTER","HÜTTE","HUTES",

  // I
  "IDEEN","IDIOM","IDIOT","IDOLE","IDOLS","IGEL","IGELS","IMKER","IMMER","INDIE",
  "INDOS","INNEN","INSEL","IRREN","IRRER","IRRES","IRRTE","ISLAM","ITAL",

  // J
  "JACKE","JÄGER","JAGEN","JAGDS","JAHRE","JAHRS","JAMME","JEDEM","JEDEN","JEDER",
  "JEDES","JEMAND","JENEM","JENEN","JENER","JENES","JETZT","JOBBE","JOCHE","JOCHS",
  "JOGGER","JOLLE","JUBEL","JUDEN","JUNGE","JUNGS","JURYS",

  // K
  "KABEL","KÄFER","KÄFIG","KAHLE","KAHLS","KAIN","KAISE","KAJAK","KAKAO","KÄLBE",
  "KÄLTE","KALTE","KAMEL","KAMIN","KAMMS","KÄMME","KAMPF","KANAL","KANNE","KANNS",
  "KANUS","KAPER","KARES","KARO","KAROS","KARPF","KARRE","KARTE","KÄSE","KÄSES",
  "KASSE","KASTE","KATER","KATZE","KAUEN","KAUFE","KAUFS","KAUFT","KEGEL","KEHLE",
  "KEHRE","KEHRT","KEILE","KEILS","KEIMS","KEINE","KEKSE","KELCH","KELLE","KENNE",
  "KENNT","KERBE","KERLE","KERLS","KERNE","KERNS","KERZE","KETTE","KIDS","KIELE",
  "KIESE","KIESS","KILOS","KIPPE","KIRSCH","KISTE","KITSCH","KITZE","KLAGE","KLAGT",
  "KLAMM","KLANG","KLAR","KLARE","KLARS","KLAUE","KLEBE","KLEBT","KLEID","KLEIE",
  "KLEIN","KLICK","KLIMA","KLOTZ","KLUFT","KLUGE","KLUGS","KNALL","KNAPP","KNAUF",
  "KNECHT","KNEIF","KNICK","KNIEN","KNIES","KNIFF","KNOPF","KNOTE","KOBOLD","KOCHE",
  "KOCHT","KOFFER","KOHLE","KOHLS","KOMET","KOMIK","KOMMA","KOMMS","KOMMT","KONUS",
  "KÖPFE","KOPFS","KOPIE","KÖRBE","KORBS","KÖRNE","KORNS","KOSEN","KOSTE","KOSTS",
  "KOSTT","KÖTER","KRACH","KRAFT","KRÄHE","KRAMS","KRANK","KRANZ","KRAUS","KRAUT",
  "KREBS","KREDIT","KREIDE","KREIS","KREUZ","KRIEG","KRIMI","KRONE","KRÖTE","KRUMM",
  "KÜBEL","KÜCHE","KUCHEN","KUGEL","KÜHLE","KÜHLS","KÜHNE","KULTUR","KUMMER","KUMPEL",
  "KUNDE","KUNST","KUPFE","KUPPE","KURBEL","KÜRBIS","KURDE","KURIE","KURVE","KURZE",
  "KURZS","KÜSSE","KUSSE","KÜSTE",

  // L
  "LACHE","LACHS","LADEN","LADET","LADUNG","LAGEN","LAGER","LÄGER","LAHME","LAICH",
  "LAIEN","LAMPE","LANDE","LANDS","LANGE","LANGS","LANZE","LAPPE","LARGO","LARVE",
  "LASCH","LASEN","LASSE","LÄSST","LASSO","LASTE","LASTS","LAUBE","LAUCH","LAUFE",
  "LÄUFE","LÄUFT","LAUGE","LAUNE","LAUTE","LAUTS","LAVAS","LAVA","LEBEN","LEBER",
  "LEBT","LECKE","LEDER","LEERE","LEERS","LEGEN","LEGT","LEHRE","LEHRS","LEIBE",
  "LEIDE","LEIER","LEIHE","LEIHS","LEIME","LEIMS","LEINE","LEISE","LEITE","LENDE",
  "LENZ","LESEN","LIEBE","LIEBT","LIEGE","LIEGT","LIFTS","LIKÖR","LILA","LILIE",
  "LIMIT","LINDE","LINIE","LINKE","LINSE","LIPPE","LISTE","LITER","LOBE","LOBEN",
  "LOBT","LOCKE","LOGIK","LÖHNE","LOHNE","LOHNT","LOREN","LOSEN","LOSER","LOSES",
  "LOSSE","LOSUNG","LOTSE","LOTTE","LOTTO","LÖWE","LÖWEN","LUCHS","LÜCKE","LÜGEN",
  "LUKEN","LUNGE","LUNTE","LUPEN","LUSTE","LÜSTE","LUSTS","LUTHE","LUTSCH",

  // M
  "MACHE","MACHT","MAGEN","MAGER","MAGIE","MAHNE","MAHNT","MAIEN","MAISE","MAJOR",
  "MAKEL","MALEN","MALER","MALES","MALTE","MAMA","MAMAS","MAMMA","MANGE","MANGO",
  "MANNS","MAPPE","MARK","MARKE","MARKS","MARS","MARSCH","MASKE","MASSE","MASTE",
  "MASTS","MATTE","MAUER","MAULS","MÄULE","MAUSE","MÄUSE","MEDIA","MEERE","MEERS",
  "MEHLE","MEHRE","MEHRS","MEIER","MEILE","MEINE","MEINS","MEINT","MEISE","MEIST",
  "MELDE","MELDT","MENGE","MENSCH","MERKE","MERKT","MESSE","METER","METRO","MIENE",
  "MIESE","MIETE","MILBE","MILCH","MILDE","MIMEN","MINEN","MINUS","MINZE","MITTE",
  "MIXEN","MIXER","MÖBEL","MODEN","MODES","MOHN","MOHNE","MONDE","MONDS","MOOR",
  "MOORE","MOPED","MORAL","MORD","MORDS","MOSES","MOTOR","MÖWE","MÖWEN","MÜCKE",
  "MÜDE","MÜHE","MÜHEN","MÜHLE","MULDE","MUMIE","MÜNDE","MUNTER","MÜNZE","MUSEN",
  "MUSIK","MUSSE","MUSTER","MUTIG","MUTTER","MÜTZE",

  // N
  "NABEL","NACHT","NACKT","NADEL","NAGEL","NAGER","NAHEN","NAHEM","NAHER","NAHES",
  "NAHME","NAMEN","NAMES","NAPF","NARBE","NARRE","NASEN","NEBEL","NEBEN","NEFFE",
  "NEHME","NEHMT","NEIGE","NEIGT","NERV","NERVS","NERZE","NESTE","NESTS","NETTE",
  "NETTS","NETZE","NETZS","NEUEM","NEUEN","NEUER","NEUES","NIERE","NIESE","NIETE",
  "NIMMT","NOBEL","NOMEN","NORD","NORMA","NORMS","NÖTIG","NOTEN","NOTES","NOTIZ",
  "NUDEL","NULLE","NÜSSE","NUTZE","NUTZT",

  // O
  "OASEN","OBEN","OBERE","OBERS","ODEM","ÖFEN","OFENS","OFFEN","OHREN","OHRS",
  "OKAY","ÖKO","OLIVE","OMAS","OMEGA","ONKEL","OPER","OPERN","OPFER","ORDEN",
  "ORGAN","ORGEL","ORKAN","ORTEN","OSTEN","OZEAN",

  // P
  "PAARE","PAARS","PACKE","PADDE","PAGEN","PAKET","PALME","PANIK","PANZE","PAPA",
  "PAPAS","PAPST","PARIS","PARKS","PARKE","PARKT","PARTY","PASSE","PASST","PASTA",
  "PATEN","PATIN","PAUKE","PAUSE","PFADE","PFADS","PFAHL","PFANNE","PFAUE","PFAUS",
  "PFEIL","PFEIFE","PFERD","PFIFF","PFLUG","PFUND","PHASE","PIANO","PILAW","PILZE",
  "PINIE","PIRAT","PIROL","PISTE","PIZZA","PLAGE","PLANE","PLANS","PLATZ","PLEITE",
  "PLUMP","PLUS","POKAL","POLEN","POLO","POLOS","POREN","POSEN","POSSE","POSTE",
  "POSTS","PRALL","PRESSE","PRIES","PRINZ","PROBE","PROFI","PROMI","PROSA","PROST",
  "PRUNK","PUDEL","PUDER","PULLI","PULSE","PULSS","PULTE","PUMPE","PUNKT","PUPPE",
  "PUTER","PUTSCH",

  // Q
  "QUALM","QUARK","QUART","QUARZ","QUASI","QUELLE","QUER","QUIRL","QUITT","QUOTE",

  // R
  "RABE","RABEN","RACHE","RACHEN","RADAR","RÄDER","RADER","RADIO","RAHM","RAHME",
  "RAND","RANDE","RANDS","RÄNGE","RANGE","RANGS","RANKE","RAPID","RAPPE","RASEN",
  "RASSE","RASTE","RATEN","RATEN","RATES","RATTE","RAUBT","RAUCH","RAUEN","RAUFE",
  "RÄUME","RAUMS","RAUPE","RAUSCH","REBEN","RECHEN","RECHT","REDEN","REGAL","REGEL",
  "REGEN","REIBE","REIBT","REICH","REIFE","REIHE","REIME","REIMS","REINE","REINS",
  "REISE","REISS","REISST","REITE","REIZE","REIZT","RENNT","RESET","RESTE","RESTS",
  "RETTE","REUEN","REVUE","RIEFE","RIEGE","RIESE","RIESS","RILLE","RINDE","RINGE",
  "RINGS","RINNE","RIPPE","RISSE","RISSS","RITTE","ROBBE","ROCKE","ROCKS","ROGEN",
  "ROHE","ROHEN","ROHER","ROHES","ROHRE","ROHRS","RÖHRE","ROLLE","ROLLT","ROMAN",
  "ROSEN","ROSES","ROSTE","ROSTS","ROTEN","ROTER","ROTES","ROUTE","RUBEL","RUBIN",
  "RUDEL","RUDER","RUFEN","RÜCKE","RÜCKT","RUHEN","RUHIG","RÜHRE","RÜHRT","RUINE",
  "RUNDE","RUNDS",

  // S
  "SAATE","SAATS","SAFTS","SÄFTE","SAGEN","SAGTE","SAITE","SALAT","SALBE","SALDO",
  "SALSA","SALTO","SALVE","SALZE","SALZS","SAMEN","SAMME","SAMTE","SANDE","SANDS",
  "SARGE","SARGS","SÄRGE","SATAN","SATIN","SAUER","SAUFE","SAUGE","SAUGT","SAUNA",
  "SAURE","SCHAF","SCHAL","SCHAM","SCHAR","SCHARF","SCHARE","SCHATZ","SCHEIN","SCHEIBE",
  "SCHELM","SCHIEN","SCHIER","SCHIFF","SCHILD","SCHIRM","SCHLAF","SCHLAG","SCHLAU","SCHLOSS",
  "SCHLUSS","SCHMAL","SCHMAH","SCHNEE","SCHNEIDE","SCHNUR","SCHOCK","SCHON","SCHOSS","SCHRECK",
  "SCHREI","SCHROT","SCHUFT","SCHUH","SCHULD","SCHULE","SCHUPP","SCHUSS","SCHUTT","SCHUTZ",
  "SCHWAN","SCHWUR","SECHS","SEELE","SEGEL","SEHEN","SEHNE","SEIDE","SEIFE","SEILE",
  "SEILS","SEKTE","SEHEN","SELBE","SENDE","SENF","SENFS","SENSE","SERIE","SETZE",
  "SETZT","SEUCHE","SICHE","SICHT","SIEBE","SIEBS","SIEGE","SIEGS","SILBE","SINGE",
  "SINGT","SINKE","SINKT","SINNE","SINNS","SITTE","SITZE","SITZT","SIRUP","SKALA",
  "SKATE","SKINS","SKIZZE","SOHN","SOHNES","SONAR","SONDE","SONNE","SONST","SORTE",
  "SOWIE","SPALT","SPANN","SPÄHT","SPALT","SPASS","SPECK","SPEER","SPIEL","SPION",
  "SPITZE","SPORN","SPORE","SPORT","SPOTT","SPRAY","SPRICH","SPRINT","SPRIT","SPRUCH",
  "SPRUNG","SPUKEN","SPULE","SPUR","SPUREN","STAAT","STÄBE","STABE","STADT","STAHL",
  "STAMM","STAND","STANGE","STARE","STARS","START","STAUB","STAUT","STAUE","STECK",
  "STEHE","STEHT","STEIF","STEIN","STELLE","STERN","STEUER","STICH","STIEFE","STIEG",
  "STIEL","STIER","STILE","STILS","STILL","STIMME","STINK","STIRN","STOCK","STOFF",
  "STOPP","STOSS","STOSST","STRAHL","STREIT","STRENGE","STRICH","STRICK","STROM","STUBE",
  "STÜCK","STUFE","STUHL","STUMM","STUNDE","STURM","STURZ","STUTE","SUCHE","SUCHT",
  "SUDEN","SÜDEN","SUITE","SUMME","SUMPF","SUPER","SUPPE","SÜSSE","SWING","SZENE",

  // T
  "TADEL","TAFEL","TAGEN","TAGES","TANNE","TANTE","TANZE","TANZT","TAPIR","TARIF",
  "TASCHE","TASSE","TASTE","TATEN","TÄTER","TATKR","TAUBE","TAUFE","TAUGT","TAXEN",
  "TAXIS","TEAMS","TEICH","TEILE","TEILS","TEILT","TELLE","TELLER","TEMPO","TENNE",
  "TERZE","TESTE","TESTS","TEUER","THEKE","THEMA","THESE","THRON","TICK","TIEFE",
  "TIERE","TIERS","TIGER","TILDE","TINTE","TIPPE","TIPPS","TIPPT","TISCH","TITAN",
  "TITEL","TOBEN","TOBT","TOMAT","TONEN","TONER","TONS","TÖPFE","TORE","TOREN",
  "TORS","TORTE","TOTAL","TOTEN","TOTER","TOTES","TOURE","TOURS","TRABS","TRACHT",
  "TRAGE","TRÄGT","TRAMP","TRÄNE","TRANK","TRAUE","TRAUT","TRAUM","TRECK","TREFF",
  "TREND","TRETE","TRICK","TRIEB","TRIO","TRIOS","TROLL","TROPF","TROST","TROTT",
  "TROTZ","TRÜBE","TRUGS","TRUST","TRUTZ","TUBA","TUBEN","TÜCHER","TUMOR","TÜRE",
  "TÜREN","TURM","TÜRME","TURMS","TUSCH","TUTTI",

  // U
  "ÜBEL","ÜBEN","ÜBER","ÜBERS","UFER","UFERN","UFERS","UHREN","UMBAU","UNGUT",
  "UNION","UNRUH","UNSER","UNTEN","UNTER","URAEL","URBAR","URNEN","URTEILE","USER",

  // V
  "VAGEN","VATER","VENUS","VERSE","VERSS","VETTER","VIDEO","VIELE","VIELS","VIERE",
  "VIERS","VIRUS","VLIES","VOGEL","VÖLKE","VOLKS","VOLLE","VOLLS","VORAB","VORN",
  "VORNE","VOTUM","VULKAN",

  // W
  "WAAGE","WACHE","WACHT","WAGEN","WÄHLE","WÄHLT","WAHRE","WAHRS","WAISE","WALDE",
  "WALDS","WÄLDE","WANDE","WANDS","WÄNDE","WANGE","WANNE","WANZE","WAREN","WARFE",
  "WARM","WÄRME","WARTE","WARTS","WARTT","WASCH","WATTE","WEBEN","WEBT","WEDER",
  "WEGEN","WEHEN","WEHRE","WEHRS","WEIBE","WEIBS","WEICH","WEIDE","WEIHE","WEINE",
  "WEINS","WEIN","WEISE","WEISS","WEITE","WEITS","WELLE","WELPE","WELTE","WELTS",
  "WENDE","WENIG","WERKE","WERKS","WERTE","WERTS","WESEN","WESTE","WETTE","WHIST",
  "WICKE","WIDER","WIESE","WILDE","WILDS","WILLE","WIND","WINDE","WINDS","WINKE",
  "WINKT","WISSE","WITWE","WITZE","WOGEN","WOGES","WOLFE","WÖLFE","WOLKE","WOLLE",
  "WOLLT","WONNE","WORTE","WORTS","WUCHS","WUNDE","WUNDS","WURDE","WÜRDE","WÜRFE",
  "WURFS","WÜRMER","WURMS","WURST","WURZE","WÜSTE","WUSST",

  // Z
  "ZACKE","ZAHLE","ZAHLS","ZAHLT","ZÄHNE","ZAHNE","ZAHNS","ZÄHME","ZAHM","ZANGE",
  "ZANKE","ZARTE","ZARTS","ZAUM","ZÄUME","ZÄUNE","ZAUNS","ZEBRA","ZECHE","ZECKE",
  "ZEHEN","ZEHNE","ZEILE","ZEITE","ZEITS","ZELLE","ZELTE","ZELTS","ZEPTER","ZETER",
  "ZEUGE","ZEUGS","ZIEGE","ZIEHE","ZIEHT","ZIELE","ZIELS","ZIERE","ZIERT","ZIMME",
  "ZINKE","ZINNS","ZINSE","ZINS","ZITAT","ZIVIL","ZOLLS","ZONEN","ZONES","ZOPFS",
  "ZÖPFE","ZORN","ZORNS","ZUCKE","ZUCKT","ZÜGE","ZÜGEL","ZUGES","ZUNGE","ZUPFE",
  "ZUSAGE","ZWANG","ZWECK","ZWERG","ZWIST"
];
